font_family FiraCode Nerd Font
font_size 8

disable_ligatures  no
enable_audio_bell  no

shell              zsh
shell_integration  disabled

cursor_shape  block

url_style    curly

remember_window_size  no
initial_window_width  640
initial_window_height 480
window_padding_width  15
cursor_blink_interval 0

background_opacity            0.75
scrollbar_handle_opacity      0
scrollbar_track_opacity       0
scrollbar_track_hover_opacity 0
confirm_os_window_close       0
#background_blur 1

sync_to_monitor no

# --- Esquema Sobrio: Deep Blue & Purple ---

# Colores Base (Fondo Azul Medianoche)
foreground            #a9b1d6
background            #0b0e14
selection_foreground  #0b0e14
selection_background  #3d5afe
cursor                #bb9af7
url_color             #7aa2f7

# Black (Gris Azulado Profundo)
color0 #15161e
color8 #414868

# Red (Rojo Desaturado)
color1 #f7768e
color9 #ff9e64

# Green (Verde Agua Frío)
color2  #73daca
color10 #b4f9f8

# Yellow (Acento Ambar)
color3  #e0af68
color11 #e0af68

# Blue (Tu color principal: Azul Cobalto)
color4  #3d5afe
color12 #7aa2f7

# Magenta (Tu color secundario: Morado Eléctrico)
color5  #9d7cd8
color13 #bb9af7

# Cyan (Azul Hielo)
color6  #7dcfff
color14 #89ddff

# White (Gris Azulado Claro)
color7  #787c99
color15 #acb0d0
